/** First-run Engram setup wizard (mini Bun.serve). */

import { $ } from "bun";
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const wizardDir = import.meta.dir;
const repoRoot = resolve(wizardDir, "..");
const serverEnvPath = join(repoRoot, "server", ".env");
const webEnvPath = join(repoRoot, "web", ".env");
const htmlPath = join(wizardDir, "index.html");

const MEMORY_LANGUAGES = ["zh-Hant", "zh-Hans", "en"] as const;
type MemoryLanguage = (typeof MEMORY_LANGUAGES)[number];
const DEFAULT_MEMORY_LANGUAGE: MemoryLanguage = "en";

function isValidIanaTimezone(tz: string): boolean {
  try {
    Intl.DateTimeFormat(undefined, { timeZone: tz });
    return true;
  } catch {
    return false;
  }
}

function isMemoryLanguage(value: unknown): value is MemoryLanguage {
  return typeof value === "string" && (MEMORY_LANGUAGES as readonly string[]).includes(value);
}

type SetupBody = {
  timezone?: string;
  memory_language?: string;
  data_home?: string;
  agent?: string;
  server_port?: number | string;
  web_port?: number | string;
  overwrite?: boolean;
};

function json(status: number, body: Record<string, unknown>): Response {
  return Response.json(body, { status });
}

function dataHomeOptions(): { id: string; path: string; label: string }[] {
  return [
    {
      id: "repo",
      path: join(repoRoot, "engram-data"),
      label: "<ENGRAM_PROGRAM>/engram-data (recommended)",
    },
    {
      id: "sibling",
      path: resolve(repoRoot, "..", "engram-data"),
      label: "<ENGRAM_PROGRAM>/../engram-data",
    },
  ];
}

function envFilesExist(): { server: boolean; web: boolean } {
  return {
    server: existsSync(serverEnvPath),
    web: existsSync(webEnvPath),
  };
}

function writeAtomic(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  const tmp = `${path}.tmp.${process.pid}`;
  writeFileSync(tmp, contents, "utf8");
  renameSync(tmp, path);
}

function buildServerEnv(input: {
  storeDir: string;
  timezone: string;
  memoryLanguage: MemoryLanguage;
  port: number;
  agent: "claude" | "cursor" | "codex";
}): string {
  return `# Generated by bun run setup — ${new Date().toISOString()}
ENGRAM_STORE_DIR=${input.storeDir}
ENGRAM_TZ=${input.timezone}
ENGRAM_MEMORY_LANGUAGE=${input.memoryLanguage}
PORT=${input.port}
ENGRAM_AGENT=${input.agent}
`;
}

function buildWebEnv(input: { webPort: number; serverPort: number }): string {
  return `# Generated by bun run setup — ${new Date().toISOString()}
WEB_PORT=${input.webPort}
ENGRAM_URL=http://localhost:${input.serverPort}
`;
}

function readProductVersion(): string {
  try {
    const line = readFileSync(join(repoRoot, "version.md"), "utf8")
      .split(/\r?\n/)
      .map((l) => l.trim())
      .find((l) => l.length > 0);
    if (line && /^\d+\.\d+\.\d+$/.test(line)) return line;
  } catch {
    /* ignore */
  }
  return "0.16.0";
}

function buildWorkspaceYaml(input: {
  timezone: string;
  memoryLanguage: MemoryLanguage;
  storeVersion: string;
}): string {
  return `# Engram workspace preferences (per memory store)
timezone: ${input.timezone}
memory_language: ${input.memoryLanguage}
store_version: ${input.storeVersion}
`;
}

function isWsl(): boolean {
  if (process.env.WSL_DISTRO_NAME || process.env.WSL_INTEROP) return true;
  try {
    return /microsoft|wsl/i.test(readFileSync("/proc/version", "utf8"));
  } catch {
    return false;
  }
}

async function openBrowser(url: string): Promise<void> {
  const platform = process.platform;
  let result: { exitCode: number } | null = null;
  try {
    if (platform === "darwin") {
      result = await $`open ${url}`.nothrow().quiet();
    } else if (platform === "win32") {
      result = await $`cmd /c start "" ${url}`.nothrow().quiet();
    } else if (isWsl()) {
      // Linux path under WSL — open via Windows host browser
      result = await $`cmd.exe /c start "" ${url}`.nothrow().quiet();
      if (result.exitCode !== 0) {
        result = await $`powershell.exe -NoProfile -Command Start-Process ${url}`.nothrow().quiet();
      }
    } else {
      result = await $`xdg-open ${url}`.nothrow().quiet();
    }
  } catch {
    result = { exitCode: 1 };
  }
  if (!result || result.exitCode !== 0) {
    console.warn(`Could not open browser automatically. Open this URL manually:\n  ${url}`);
  }
}

async function runInstalls(): Promise<void> {
  console.log("Installing server dependencies…");
  await $`bun install`.cwd(join(repoRoot, "server"));
  console.log("Installing web dependencies…");
  await $`bun install`.cwd(join(repoRoot, "web"));
}

function validateAndApply(body: SetupBody): Response {
  const fields: Record<string, string> = {};

  const timezone = typeof body.timezone === "string" ? body.timezone.trim() : "";
  if (!timezone || !isValidIanaTimezone(timezone)) {
    fields.timezone = "Choose a valid IANA timezone from the list";
  }

  const memory_language = body.memory_language;
  if (!isMemoryLanguage(memory_language)) {
    fields.memory_language = `Must be one of ${MEMORY_LANGUAGES.join(" | ")}`;
  }

  const data_home = typeof body.data_home === "string" ? body.data_home.trim() : "";
  const absOk = data_home.startsWith("/") || /^[A-Za-z]:[\\/]/.test(data_home);
  if (!data_home || !absOk) {
    fields.data_home = "Provide an absolute path for ENGRAM_STORE_DIR";
  }

  const agentRaw = body.agent;
  let agent: "claude" | "cursor" | "codex" | null = null;
  if (agentRaw === "claude" || agentRaw === "cursor" || agentRaw === "codex") agent = agentRaw;
  else fields.agent = "Choose Claude Code, Cursor CLI, or Codex CLI";

  const server_port = Number(body.server_port);
  const web_port = Number(body.web_port);
  if (!Number.isInteger(server_port) || server_port < 1 || server_port > 65535) {
    fields.server_port = "Invalid server port";
  }
  if (!Number.isInteger(web_port) || web_port < 1 || web_port > 65535) {
    fields.web_port = "Invalid web port";
  }
  if (
    Number.isInteger(server_port) &&
    Number.isInteger(web_port) &&
    server_port === web_port
  ) {
    fields.web_port = "Web port must differ from server port";
  }

  if (Object.keys(fields).length > 0) {
    return json(400, { error: "validation_failed", code: "validation_failed", fields });
  }

  const existing = envFilesExist();
  if ((existing.server || existing.web) && !body.overwrite) {
    return json(409, {
      error: "env_exists",
      code: "env_exists",
      message: "server/.env and/or web/.env already exist. Confirm overwrite to continue.",
      existing,
    });
  }

  const storeDir = resolve(data_home);
  const memoryLanguage = memory_language as MemoryLanguage;

  try {
    mkdirSync(storeDir, { recursive: true });
    writeAtomic(
      serverEnvPath,
      buildServerEnv({
        storeDir,
        timezone,
        memoryLanguage,
        port: server_port,
        agent: agent!,
      }),
    );
    writeAtomic(
      webEnvPath,
      buildWebEnv({ webPort: web_port, serverPort: server_port }),
    );
    writeAtomic(
      join(storeDir, "engram.workspace.yaml"),
      buildWorkspaceYaml({
        timezone,
        memoryLanguage,
        storeVersion: readProductVersion(),
      }),
    );
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error(`Setup write failed: ${msg}`);
    return json(500, { error: "write_failed", code: "write_failed", message: msg });
  }

  return json(200, {
    ok: true,
    store_dir: storeDir,
    timezone,
    memory_language: memoryLanguage,
    server_port,
    web_port,
    agent,
  });
}

console.log("Engram setup will install dependencies, start a local wizard, and open your browser…");
if (process.env.SETUP_SKIP_INSTALL === "1") {
  console.log("SETUP_SKIP_INSTALL=1 — skipping bun install");
} else {
  await runInstalls();
}

const server = Bun.serve({
  port: 0,
  hostname: "127.0.0.1",
  routes: {
    "/": Bun.file(htmlPath),
    "/meta": {
      GET: () =>
        json(200, {
          repo_root: repoRoot,
          data_home_options: dataHomeOptions(),
          env_exists: envFilesExist(),
          memory_languages: MEMORY_LANGUAGES,
          default_memory_language: DEFAULT_MEMORY_LANGUAGE,
          default_server_port: 8787,
          default_web_port: 8788,
        }),
    },
    "/setup": {
      POST: async (req) => {
        let body: SetupBody;
        try {
          body = (await req.json()) as SetupBody;
        } catch {
          return json(400, { error: "invalid_json", code: "invalid_json" });
        }
        const res = validateAndApply(body);
        if (res.status === 200) {
          console.log(
            "Setup wrote server/.env, web/.env, ENGRAM_STORE_DIR, and engram.workspace.yaml successfully.",
          );
          setTimeout(async () => {
            try {
              await server.stop(true);
            } catch {
              // ignore
            }
            process.exit(0);
          }, 150);
        }
        return res;
      },
    },
  },
  fetch() {
    return new Response("Not Found", { status: 404 });
  },
});

const url = `http://127.0.0.1:${server.port}/`;
console.log(`Setup wizard: ${url}`);
await openBrowser(url);
